from __future__ import annotations

from pathlib import Path

import pytest
import torch

import activation_steering as steering
from tests.test_activation_steering import make_gpt2_model, make_test_tokenizer


@pytest.fixture()
def tokenizer():
    return make_test_tokenizer()


@pytest.fixture()
def model(tokenizer):
    return make_gpt2_model(tokenizer)


@pytest.fixture()
def persistent_vectors_path():
    """Checked-in fixture regenerated by the discovery integration test."""
    return Path(__file__).parent / "data" / "minimal_identified_feature_vectors.json"


def test_load_steering_controllers_reads_persistent_vectors(persistent_vectors_path):
    controllers = steering.load_steering_controllers(
        persistent_vectors_path,
        default_alpha=1.25,
        default_decay=0.8,
        task_types_by_controller={"chain_of_thought": ["qa"]},
    )

    assert len(controllers) == 4
    chain_of_thought = next(
        controller for controller in controllers if controller.controller_id == "chain_of_thought"
    )
    assert chain_of_thought.layer_idx == 1
    assert torch.isclose(chain_of_thought.vector.norm(), torch.tensor(1.0), atol=1e-5)
    assert chain_of_thought.task_types == ("qa",)
    assert chain_of_thought.alpha == pytest.approx(1.25)
    assert chain_of_thought.decay == pytest.approx(0.8)


def test_steered_executor_collects_trace_and_runs_selected_controller(
    model, tokenizer, persistent_vectors_path
):
    controllers = steering.load_steering_controllers(
        persistent_vectors_path,
        task_types_by_controller={
            "retrieval_augmented_context": ["qa"],
            "chain_of_thought": ["qa"],
        },
    )
    memory = steering.InMemorySteeringMemory(controllers)
    controller = memory.get_controller("chain_of_thought")
    executor = steering.SteeredExecutor(
        model=model,
        tokenizer=tokenizer,
        model_name="gpt2",
        top_k_trace_features=2,
    )
    plan = steering.PlannerDecision(task_type="qa", needs_retrieval=True, controller_id=None)

    result = executor.execute(
        task="Question: What is the capital of France?\nAnswer:",
        plan=plan,
        context=["Evidence: Paris is the capital of France."],
        controller=controller,
        controllers=memory.list_controllers(),
        max_new_tokens=3,
    )

    assert result.controller_id == "chain_of_thought"
    assert "Evidence: Paris is the capital of France." in result.prompt
    assert isinstance(result.output_text, str)
    assert result.activation_trace is not None
    assert result.activation_trace.controller_id == "chain_of_thought"
    assert len(result.activation_trace.top_feature_scores) == 2
    assert {
        score.feature_id for score in result.activation_trace.top_feature_scores
    }.issubset({controller.controller_id for controller in controllers})


def test_in_memory_steering_memory_prefers_most_successful_controller_for_task_type():
    first = steering.SteeringController(
        controller_id="first",
        feature_name="first",
        layer_idx=0,
        vector=torch.tensor([1.0, 0.0]),
        task_types=("qa",),
    )
    second = steering.SteeringController(
        controller_id="second",
        feature_name="second",
        layer_idx=0,
        vector=torch.tensor([0.0, 1.0]),
        task_types=("qa",),
    )
    memory = steering.InMemorySteeringMemory([first, second])
    plan = steering.PlannerDecision(task_type="qa")
    verdict_fail = steering.VerifierResult(passed=False, confidence=0.2)
    verdict_pass = steering.VerifierResult(passed=True, confidence=0.9)

    memory.record_run(
        steering.HybridAgentRun(
            task="question one",
            plan=plan,
            context=[],
            draft=steering.ExecutorResult(prompt="q1", output_text="bad", controller_id="first"),
            verdict=verdict_fail,
            selected_controller_id="first",
        )
    )
    memory.record_run(
        steering.HybridAgentRun(
            task="question two",
            plan=plan,
            context=[],
            draft=steering.ExecutorResult(prompt="q2", output_text="good", controller_id="second"),
            verdict=verdict_pass,
            selected_controller_id="second",
        )
    )

    selected = memory.select_controller(task_type="qa")

    assert selected is not None
    assert selected.controller_id == "second"
    assert memory.controller_success_rate("qa", "first") == pytest.approx(0.0)
    assert memory.controller_success_rate("qa", "second") == pytest.approx(1.0)


def test_controller_success_rate_returns_none_before_first_run():
    controller = steering.SteeringController(
        controller_id="untested",
        feature_name="untested",
        layer_idx=0,
        vector=torch.tensor([1.0, 0.0]),
        task_types=("qa",),
    )
    memory = steering.InMemorySteeringMemory([controller])

    selected = memory.select_controller(task_type="qa")

    assert selected is not None
    assert selected.controller_id == "untested"
    assert memory.controller_success_rate("qa", "untested") is None


def test_hybrid_meta_cognition_agent_falls_back_and_records_memory():
    controller = steering.SteeringController(
        controller_id="retrieval_augmented_context_v1",
        feature_name="retrieval_augmented_context",
        layer_idx=0,
        vector=torch.tensor([1.0, 0.0]),
        task_types=("qa",),
    )
    memory = steering.InMemorySteeringMemory([controller])

    class StubExecutor:
        def __init__(self):
            self.calls = []

        def execute(self, task, plan, context, controller=None, controllers=(), max_new_tokens=80):
            self.calls.append(controller.controller_id if controller else None)
            return steering.ExecutorResult(
                prompt=f"task={task}\ncontext={' | '.join(context)}",
                output_text="steered answer" if controller else "fallback answer",
                controller_id=controller.controller_id if controller else None,
                activation_trace=steering.ActivationTrace(
                    model_name="stub-model",
                    controller_id=controller.controller_id if controller else None,
                    layer_idx=controller.layer_idx if controller else None,
                    prompt="stub prompt",
                    top_feature_scores=[],
                ),
            )

    executor = StubExecutor()

    def planner(task, memory_store):
        return steering.PlannerDecision(
            task_type="qa",
            needs_retrieval=True,
            use_steering=True,
            allow_fallback=True,
        )

    def retriever(task, plan):
        return ["Evidence: retrieved fact"]

    def tool_router(task, plan, context):
        return ["Tool observation: retrieved tool output"]

    def verifier(task, draft, context, plan):
        return steering.VerifierResult(
            passed=draft.controller_id is None,
            confidence=0.9 if draft.controller_id is None else 0.1,
            issues=[] if draft.controller_id is None else ["needs fallback"],
        )

    agent = steering.HybridMetaCognitionAgent(
        planner=planner,
        retriever=retriever,
        tool_router=tool_router,
        executor=executor,
        verifier=verifier,
        memory=memory,
    )

    run = agent.run("What is the capital of France?")

    assert run.fallback_used is True
    assert run.selected_controller_id == "retrieval_augmented_context_v1"
    assert run.draft.output_text == "fallback answer"
    assert run.verdict.passed is True
    assert run.context == [
        "Evidence: retrieved fact",
        "Tool observation: retrieved tool output",
    ]
    assert executor.calls == ["retrieval_augmented_context_v1", None]
    assert len(memory.run_history) == 1
