"""Reusable activation steering helpers for decoder-only Hugging Face models."""

from .catalog import (
    STANDARD_ACTIVATION_CATALOG_PATH,
    STANDARD_ACTIVATIONS_PATH,
    get_standard_activation_models,
    get_standard_activations,
    load_standard_activation_catalog,
)
from .discovery import (
    DiscoveredFeatureVector,
    discover_and_store_feature_vectors,
    discover_feature_vectors,
    save_discovered_feature_vectors,
)
from .evaluation import collect_evaluation_rows
from .features import (
    STANDARD_FEATURE_CATALOG_PATH,
    STANDARD_FEATURE_SPECS_PATH,
    EvaluationCriterion,
    FeatureCatalog,
    FeatureExample,
    FeatureSpec,
    build_feature_spec,
    get_standard_feature_catalog,
    get_standard_feature_models,
    get_standard_feature_specs,
    load_standard_feature_catalogs,
)
from .models import (
    DEFAULT_DO_SAMPLE,
    DEFAULT_MAX_NEW_TOKENS,
    collect_last_token_hiddens,
    generate,
    get_default_device,
    get_hidden_states,
    get_last_token_hidden,
    get_model_device,
    get_transformer_blocks,
    get_transformer_layers,
    load_model_and_tokenizer,
    tokenize_text,
)
from .steering import (
    ActivationSteerer,
    AdaptiveActivationSteerer,
    build_mean_difference_vector,
    cosine,
    generate_with_adaptive_steering,
    generate_with_steering,
    train_probe,
)

__all__ = [
    "ActivationSteerer",
    "AdaptiveActivationSteerer",
    "DEFAULT_DO_SAMPLE",
    "DEFAULT_MAX_NEW_TOKENS",
    "DiscoveredFeatureVector",
    "EvaluationCriterion",
    "FeatureCatalog",
    "FeatureExample",
    "FeatureSpec",
    "STANDARD_ACTIVATION_CATALOG_PATH",
    "STANDARD_ACTIVATIONS_PATH",
    "STANDARD_FEATURE_CATALOG_PATH",
    "STANDARD_FEATURE_SPECS_PATH",
    "build_feature_spec",
    "build_mean_difference_vector",
    "collect_evaluation_rows",
    "collect_last_token_hiddens",
    "cosine",
    "discover_and_store_feature_vectors",
    "discover_feature_vectors",
    "generate",
    "generate_with_adaptive_steering",
    "generate_with_steering",
    "get_default_device",
    "get_hidden_states",
    "get_last_token_hidden",
    "get_model_device",
    "get_standard_activation_models",
    "get_standard_activations",
    "get_standard_feature_catalog",
    "get_standard_feature_models",
    "get_standard_feature_specs",
    "get_transformer_blocks",
    "get_transformer_layers",
    "load_standard_activation_catalog",
    "load_standard_feature_catalogs",
    "load_model_and_tokenizer",
    "save_discovered_feature_vectors",
    "tokenize_text",
    "train_probe",
]
